# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: FRC 中文 Wiki

repo_name: FRC-China/FRC-Wiki
repo_url: https://github.com/CLCK0622/FRC-Wiki

nav:
  - 关于本站:
      - 关于本项目: index.md
      - 如何使用本项目: start/usage.md
      - 如何参与: start/contribute.md
      - FAQ: start/faq.md
      - 致谢: start/acknowledgement.md
  - FRC 简介:
      - 比赛历史: intro/history.md
      - 比赛内容: intro/content.md
      - 外网资源: intro/resources.md
  - 机械结构:
      - 结构概述: structure/overview.md
  - 电控系统:
      - 电控概述: electronics/overview.md
  - 程序:
      - 程序概述: programming/overview.md
      - Java 基础: programming/java-basics.md
  - 最佳实践:
        - 概述: best-practices/overview.md

markdown_extensions:
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - search.suggest
    - navigation.footer

copyright: Copyright &copy; 2023 FRC China Wiki Team
